from class_txt import*
a=Text("salom.txt")
a.read_text()
a.write_text("Bu text \npython dastrulash tili\nkursidan vazifa")
a.read_text()
a.add_text("sana 10-yanvar\n2024-yil")
a.read_text()
a.first_row()
a.massiv()
print()
print(a[1])
a[1]="kod"
print(a[1])
a.del_abzas()
a.read_text()
print(a)
obyekt=Text('obyekt.txt')
obyekt.add_text("bu obyekt \nfayl\nfaqat uyg'otish uchun\nyaratildi\npython fayl bu\nclasslar uchun")
a("obyekt.txt")
a.read_text()
a.upper_row()
a.read_text()
a.upper_word()
a.read_text()
a.del_row(1)
a.read_text()
a.get_row(2)
print()
a.get_rows(2,3)
print()
a.del_rows(2,3)
a.read_text()
a.new_file(2,3)
a.padding_left(3)
a.read_text()
a.append_file("new_file.txt")
a.read_text()