from classlar import*
a=ishchi("Matnazar","+998918690730","IT kompaniyasi","15 yil")
a.get_info()
s="18 yil"
a.update_staji(s)
a.get_info()
a=Jurnal("Gulhan","bir haftada bir marta","rangli","2023.12.20")
a.get_info()
s="Darakchi"
a.set_nomi(s)
a.get_info()
a=Mahsulot("kompyuter",100000000,"Uzb")
a.get_info()
a.set_narxi(20)
a.get_info()
a=kivitasiya('+998918690730','2022','15 million','Amerika')
a.get_info()
a.set_manzil("Uzbekiston")
a.get_info()
a=Tikuvchilik_sexi('Gulzoda','yordamchi',17,'Al uz')
a.get_info()
a.set_ishchi_soni(19)
a.get_info()
a=shaxs('Albert',61,'erkak','ingiliz')
a.get_info()
a.set_millat('rus')
a.get_info()
a=korabl('Shoxjaxon',111,"a'lo",19)
a.get_info()
a.set_turi('qoniqarli')
a.get_info()
a=shahar('Xiva','Uzbekistan','Xiva tumani',"a'lo")
a.get_info()
a.set_nomi('Urganch')
a.get_info()
a=tasvir('Monaliza','Leonarda','1503','galereya aniqmas')
a.get_info()
a.set_yili('1506')
a.get_info()
a=ijarachi('Azizbek','Uzbekistan',20,'Olimpiada')
a.get_info()
a.update_yoshi()
a.get_info()
a=telefon('Matnazar','+998918690731','Xiva','Beeline')
a.get_info()
a.set_raqami('998918690730')
a.get_info()
a=futbolchi('Sherzod',19,'darvozabon',3)
a.get_info()
a.set_gollar_soni(4)
a.get_info()
a=disk('SSD',256,350000,'Uzbekistan')
a.get_info()
a.set_narxi(450000)
a.get_info()
a=ustoz('Shahzod',29,2,'9-D')
a.get_info()
a.set_sinf('9-A')
a.get_info()
a=fan('Matematika',129,2,'Algebra')
a.get_info()
a.set_kurs(1)
a.get_info()