from classlar import *
fayl=Word('fayl_word.docx')
fayl.add_text("Mavzu : Pythonda Word ochish")
fayl.read_text()
fayl.add_heading("Bugungi sana : 14.01.2024")
fayl.add_text("Reja : 1")
fayl.read_text()
fayl.first_paragraf()
fayl.massiv()
print(fayl)
fayl(1)
fayl.del_paragraf(0)
fayl.read_text()
fayl.write_text('Dars tugadi')
fayl.read_text()
fayl.saqlash('fayl_word.docx')